// <auto-generated />
using System;
using AeroSoilAI.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AeroSoilAI.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529164828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroSoilAI.Api.Models.Propriedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PROPRIEDADE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Hectares")
                        .HasPrecision(10, 2)
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("NR_HECTARES");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DS_LOCALIZACAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("NM_PROPRIEDADE");

                    b.HasKey("Id");

                    b.ToTable("TB_PROPRIEDADE", (string)null);
                });

            modelBuilder.Entity("AeroSoilAI.Api.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ATUALIZACAO");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PROPRIEDADE");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("TP_SENSOR");

                    b.Property<decimal>("UltimaLeitura")
                        .HasPrecision(10, 2)
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VL_ULTIMA_LEITURA");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("TB_SENSOR", (string)null);
                });

            modelBuilder.Entity("AeroSoilAI.Api.Models.Sensor", b =>
                {
                    b.HasOne("AeroSoilAI.Api.Models.Propriedade", "Propriedade")
                        .WithMany("Sensores")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AeroSoilAI.Api.Models.Propriedade", b =>
                {
                    b.Navigation("Sensores");
                });
#pragma warning restore 612, 618
        }
    }
}
